### ISSUE TITLE
Carany CI needs fixes

### ISSUE THREAD

**Issue by JesperDramsch** [ecmwf/anemoi-utils#64]
### What happened?

The changelog updater fails in the absence of a release title.
The changelog checker was commented out instead of deleted, which leads to consistent failures. Should be deleted.

We can also test the use of an automated labelling workflow and using `release.yml`

### What are the steps to reproduce the bug?

Failing action runs.

### Version

Current

### Platform (OS and architecture)

Github Actions

### Organisation

ECMWF

**Comment by HCookie** [comment]
I assume this can be closed given #67 ?

**Comment by JesperDramsch** [comment]
Absolutely!
